### ISSUE TITLE
ECR Repository

### ISSUE THREAD

**Issue by kikobr82** [devopsacademyau/2020-feb-project1-group2#20]
Objectives:  
- create a custom ECR repository for hosting custom wordpress container image
  - you can use official wordpress image but from a custom Dockerfile (i.e. FROM wordpress) - not latest though - please fix a wordpress version
  - make sure to push at least the first version of it to the new ecr

Acceptance criteria:
  - I can push new container image tags to an ECR repository
  - I can pull images on ECR from EC2 instances running on my VPC
  - I can pull images on ECR from my local

**Comment by faria-marcio** [comment]
**Amazon ECR - Adding Repository via terraform:**
    https://www.terraform.io/docs/providers/aws/r/ecr_repository.html

**Amazon ECR - Adding Repository Policies via terraform:**
    https://www.terraform.io/docs/providers/aws/r/ecr_repository_policy.html

**Amazon ECR Repository Policies:**
    https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-policies.html

**Amazon ECR Repository Policy Examples:**
    https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-policy-examples.html

**Amazon ECR - Pushing an Image:**
    https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html
    ps.: Use the commands provided on ECR > Repositories > Image (in this case wp-image) > View push commands Button, because it provides the same information as above + the specific commands to our image.

**Amazon ECR - Pulling an Image:**
    https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-pull-ecr-image.html
