### ISSUE TITLE
Wordpress Application

### ISSUE THREAD

**Issue by kikobr82** [devopsacademyau/2020-feb-project1-group2#23]
Objectives:
  - task definition:
    - custom wordpress image from ECR
    - using efs as volume and mounting `/var/www/html` inside wordpress container for persistent storage
      - no need for IAM authentication
    - wordpress database variables coming from ssm parameter store
    - memory 128
    - any IAM execution role if needed with only required permissions
  - ecs service:
    - type EC2
    - use custom task definition for wordpress
    - service type replica
    - deployment type rolling update or blue/green (first is easier, second is better)
    - at least 2 task definitions running at any point in time
  - initialise wordpress database when first runs a container

Acceptance Criteiria:
  for testing purposes:
  - run a test ecs cluster with instances running on public subnet and required security groups open
  - run service with only one task definition running exposed to port 80
  - access public ip address from ec2 instance on port 80 to reach wordpress running
  - finish wordpress installation steps to initialise database
  terraform code:
  - service needs 2 task definitions running
  - don't expose task definition to port 80 on host

**Comment by Faria-Marcio** [comment]
Hi @drii-cavalcanti, 
I just saw that you self-assigned for this card, so I'm wondering if you already worked on it. If so, I'll jump in another card that is still pending.

Thanks

**Comment by faria-marcio** [comment]
@drii-cavalcanti as you are working in this card, I'll jump in another one.

Thanks and let me know if you need any help.
