### ISSUE TITLE
ECS Cluster

### ISSUE THREAD

**Issue by starkmatt** [devopsacademyau/2020-feb-project1-group2#8]
Objectives:
  - ecs cluster using autoscaling group
    - 1 instance is fine for demonstration, 2 ideal
    - t2.micro should be fine (if possible)
  - use amazon linux image 2 for ecs
  - hosted on private subnets
  - any security groups needed
  - any IAM instance role needed

Acceptance Criteria:
  - I can see a cluster on AWS console with at least one instance available, ideally two instances on different AZ's
  - cluster instances should be running on private subnet
  - instances should be running Amazon Linux 2 optimised for ECS
  - any security group or IAM permissions should be very restrictive with only required permissions
  - terraform code should use VARIABLES for most of the settings

**Comment by kikobr82** [comment]
Add what is being delivered on this card.
What resources will be added in the terraform?

**Comment by starkmatt** [comment]
Have found the following post

https://github.com/anrim/terraform-aws-ecs

They've really simplified the ECS Process.
Currently troubleshooting some issues with the user data shell script.

Terraform will init but not plan

**Comment by starkmatt** [comment]
ECS Cluster has been created in this pull request.
Please review and advise

<s>https://github.com/devopsacademyau/2020-feb-project1-group2/pull/11</s>

New PR

https://github.com/devopsacademyau/2020-feb-project1-group2/pull/19

**Comment by faria-marcio** [comment]
I've created the ECS security group in the PR #39 because I needed it to create the EFS security group. I haven't created the rules, so it needs to be reviewed and updated.
